import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src='/sc.js' strategy='lazyOnload'></Script> */}
      
      
      <main className={styles.main}>
        <h1 className={styles.title}>
          Hunting Coder
        </h1>
        <div className={styles.imgWrp}>
        <Image className={styles.imgCore} src="/coder.webp" width={180} height={180}></Image>
        </div>
       
        <p className={styles.description}>
          Bill Vol Bill
        </p>


      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
